applications:
- application_name: Portal web
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://mbfs.latinid.com.mx:9582/login
  type: web
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
